import {StyleSheet} from 'react-native';
import Metrics from '../metrics';
export default StyleSheet.create({
  container: {
    flex: 1,
    width: '100%',
    backgroundColor: 'white',
    paddingTop: Metrics.barHeight,
  },
  headerButton: {
    width: 50,
    position: 'absolute',
    top: Metrics.barHeight + 5,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  main: {
    width: '100%',
    position: 'absolute',
    top: 0,
    alignItems: 'center',
    // paddingTop: Metrics.barHeight,
    left: 0,
    right: 0,
    height: Metrics.height * 0.6,
  },
  listHeader: {
    // zIndex: 5,
    width: '100%',
    height: Metrics.height - (Metrics.isAndroid ? 80 : 60) - Metrics.barHeight,
    position: 'absolute',
    zIndex: 5,
    // justifyContent: 'center',
    borderTopLeftRadius: 40,
    top: Metrics.height * 0.6,
    borderTopRightRadius: 40,
    backgroundColor: 'black',
  },
  listTitle: {
    color: 'white',
    fontSize: 22,
    fontWeight: 'bold',
  },
  profileImage: {
    width: 150,
    height: 150,
    borderRadius: 75,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: 'black',
    marginTop: 120,
  },
  proImage: {
    width: 130,
    height: 130,
    borderRadius: 70,
    overflow: 'hidden',
  },
  image: {
    flex: 1,
    width: null,
    height: null,
  },
  activeIndicator: {
    width: 20,
    height: 20,
    borderRadius: 10,
    zIndex: 2,
    bottom: 15,
    left: 15,
    position: 'absolute',
    backgroundColor: 'lightgreen',
  },
  mainName: {
    fontSize: 26,
    fontWeight: 'bold',
    marginTop: 15,
    marginBottom: 10,
  },
  mainFrom: {
    fontSize: 16,
    fontWeight: '600',
    color: 'rgba(0,0,0,0.6)',
    marginBottom: 15,
  },
  followInfo: {
    width: '50%',
    height: 80,
    flexDirection: 'row',
  },
  followers: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
  },
  box: {
    flex: 1,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.1)',
  },
  boxContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  followText: {
    fontSize: 16,
    color: 'rgba(0,0,0,0.6)',
  },
  description: {
    width: '100%',
    alignItems: 'center',
  },
  listHeaderContainer: {
    paddingHorizontal: 40,

    paddingVertical: 30,
    alignSelf: 'stretch',
    // paddingHorizontal: 30,
  },
  listItem: {
    width: '100%',
    height: 500,
    backgroundColor: 'black',
    paddingHorizontal: 10,
    paddingVertical: 20,
    borderRadius: 20,
  },
  separator: {
    width: '100%',
    height: 2,
    backgroundColor: '#232323',
  },
  itemHeader: {
    height: 70,
    alignItems: 'center',
    width: '100%',
    flexDirection: 'row',
  },
  itemProfileImage: {
    width: 50,
    height: 50,
    borderRadius: 25,
  },
  itemHeaderTitle: {
    flex: 1,
    paddingHorizontal: 20,
    justifyContent: 'space-evenly',
  },
  name: {
    color: 'white',
    fontSize: 14,
  },
  added: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 12,
  },
  itemDescription: {
    flex: 1,
  },
  bottomBox: {
    flex: 1,
    borderRadius: 20,
    overflow: 'hidden',
    height: '100%',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  likeText: {
    color: 'white',
    fontSize: 12,
  },
  itemImage: {
    flex: 1,
    width: null,
    height: null,
    borderRadius: 30,
  },
  itemDesc: {
    width: '100%',
    paddingHorizontal: 10,
    paddingVertical: 20,
  },
  descText: {
    fontSize: 14,
    color: 'white',
  },
  listContainer: {
    // paddingBottom: 10,
    backgroundColor: '#232323',
  },
});
